accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path,include
from accounts import views

app_name = "accounts"

urlpatterns = [
    
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    
    path("password_change/",views.PasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/",views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    path("password_reset/",views.PasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/",views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/",views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/",views.PasswordResetComleteView.as_view(), name="password_reset_complete"),

 
    path("profile/create/", views.ProfileCreateView.as_view(), name="profile_create"),
    path("profile/<int:pk>/", views.ProfileDetailView.as_view(), name="profile_detail"),
    path("profile/<int:pk>/update/", views.ProfileUpdateView.as_view(), name="profile_update"),
    path("employer/profile/create/", views.EmpprofileCreateView.as_view(), name="profile"),
    path("employer/profile/<int:pk>/", views.EmployerProfileDetailView.as_view(), name="employer_profile_detail"),
    path("employer/profile/<int:pk>/update/", views.EmployerProfileUpdateView.as_view(), name="employer_profile_update"),
    path("add/", views.AddEmployerView.as_view(), name="create"),

    #path("dashboard/", views.DashboardView.as_view(), name="dashboard"),

    #employers
    path("employers/", views.EmployerListView.as_view(), name="employer_list"),
    path("employers/<int:pk>/detail/", views.EmployerDetailView.as_view(), name="employer_detail"),
    path("employers/<int:pk>/update/", views.EmployerUpdateView.as_view(), name="employer_update"),
    path("employers/<int:pk>/delete/", views.EmployerDeleteView.as_view(), name="employer_delete"),

    ]

core/urls.py
from django.urls import path
from core import views

app_name = "core"
urlpatterns = [
    path("", views.HomeView.as_view(),name="home"),
    path("adminhome/", views.AdminHomeView.as_view(),name="ahome"),
    path("emprhome/", views.EmployerHomeView.as_view(),name="ehome"),
    path("userhome/", views.UserHomeView.as_view(),name="uhome"),
    path("search/", views.SearchView.as_view(),name="search"),
    #jobpost

    path("jobpost/create/", views.JobPostCreateView.as_view(), name="jobpost_create"),
    path("jobposts/list/", views.JobpostListView.as_view(), name="jobpost_list"),
    path("jobposts/list/?category=<int:pk>", views.JobpostListByCategoryView.as_view(), name="jobpost_list_by_category"),
    path("jobposts/<int:pk>/detail/", views.JobpostDetailView.as_view(), name="jobpost_detail"),
    path("jobposts/<int:pk>/update/", views.JobpostUpdateView.as_view(), name="jobpost_update"),
    path("jobposts/<int:pk>/delete/", views.JobpostDeleteView.as_view(), name="jobpost_delete"),
    path("jobposts/<int:pk>/detail/", views.DetailView.as_view(), name="more"),
    path("jobposts/<int:pk>/apply/", views.AppliedJobCreateView.as_view(), name="jobpost_apply"),

    # Applied job
    path("applied-job/<int:pk>/", views.AppliedJobDetailView.as_view(), name="applied_job_detail"),
    path("applied-job/list/", views.AppliedListView.as_view(), name="applied_job_list"),
    path("myapplied/list/", views.MyAppliedListView.as_view(), name="myapplied_list"),

   
   # path("login/", views.LoginView.as_view(), name="login"),
   # path("register/", views.LoginView.as_view(), name="register"),
]

dream_catcher/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls',namespace="core")),
    path("accounts/", include("accounts.urls", namespace="accounts")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/views.py
from typing import Any, Dict

from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic as views

from core import forms, models

# from accounts import forms, models
category = [
    {
        "name": "Marketing",
        "no of vacancy": "20",
        "image": "/media/default/logo.png",
    },
    {
        "name": "Customer Service",
        "no_of_vacancy": "20",
        "image": "/media/default/logo.png",
    },
    {
        "name": "HR",
        "no_of_vacancy": "20",
        "image": "/media/default/logo.png",
    },
    {
        "name": "Project Management",
        "no_of_vacancy": "20",
        "image": "/media/default/logo.png",
    },
]

common_data = {
    "project_name": "Dream_Catcher",
    "page_name": "Home",
}


class HomeView(views.TemplateView):
    template_name = "core/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        catergories = models.Category.objects.all()
        context["categories"] = catergories
        context.update(common_data)
        return context


class SearchView(views.TemplateView):
    template_name = "search.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        kw = self.request.GET["keyword"]
        result = models.JobPostModel.objects.filter(post_name__icontains=kw)
        print(result)
        context["results"] = result

        return context


class AdminHomeView(LoginRequiredMixin, PermissionRequiredMixin, views.TemplateView):
    template_name = "core/admin_home.html"
    extra_context = {
        "project_name": "Dream_Catcher",
        "page_name": "Admin Home",
    }
    permission_required = []
    permission_denied_message = "You are not allowed to view this page"

    def has_permission(self) -> bool:
        permitted = self.request.user.is_superuser and super().has_permission()
        return permitted


class EmployerHomeView(views.TemplateView):
    template_name = "core/empr_home.html"
    extra_context = {
        "project_name": "Dream_Catcher",
        "page_name": "employer Home",
    }


class UserHomeView(views.TemplateView):
    template_name = "core/user_home.html"
    extra_context = {
        "project_name": "Dream_Catcher",
        "page_name": "User Home",
    }


class JobPostCreateView(LoginRequiredMixin, views.CreateView):
    template_name = "core/jobpost/jobpost_create.html"
    model = models.JobPostModel
    form_class = forms.JobPostForm
    success_url = reverse_lazy("core:jobpost_list")
    context_object_name = "jobpost"

    def get_form_kwargs(self) -> Dict[str, Any]:
        kwargs = super().get_form_kwargs()
        if hasattr(self.request.user, "employermodel"):
            kwargs.update(
                {
                    "initial": {
                        "company_name": self.request.user.employermodel.company_name,
                    }
                }
            )
        return kwargs

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.posted_by = self.request.user
        return super().form_valid(form)


class JobpostListView(views.ListView):
    template_name = "core/jobpost/jobpost_list.html"
    model = models.JobPostModel
    context_object_name = "jobposts"

    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset()

        employer = getattr(self.request.user, "employermodel", False)
        if employer:
            qs = qs.filter(posted_by=self.request.user)

        return qs


class JobpostDetailView(views.DetailView):
    template_name = "core/jobpost/jobpost_detail.html"
    model = models.JobPostModel
    context_object_name = "jobpost"


class JobpostUpdateView(views.UpdateView):
    template_name = "core/jobpost/jobpost_update.html"
    model = models.JobPostModel
    form_class = forms.JobPostForm
    success_url = reverse_lazy("core:jobpost_list")


class JobpostDeleteView(views.DeleteView):
    template_name = "core/jobpost/jobpost_delete.html"
    model = models.JobPostModel
    success_url = reverse_lazy("core:jobpost_list")
    context_object_name = "jobpost"


class JobpostListByCategoryView(views.ListView):
    template_name = "core/jobpost/jobpost_list.html"
    model = models.JobPostModel
    context_object_name = "jobposts"

    def get_queryset(self) -> QuerySet[Any]:
        q = super().get_queryset()
        q.filter(id=self.kwargs.get("pk"))
        return q


class DetailView(views.DetailView):
    template_name = "details.html"
    model = models.JobPostModel
    context_object_name = "jobpost"


class AppliedJobCreateView(LoginRequiredMixin, views.CreateView):
    template_name = "applied.html"
    model = models.AppliedModel
    form_class = forms.AppliedForm
    context_object_name = "jobpost"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        jobpost_id = self.kwargs.get("pk")
        self.jobpost = models.JobPostModel.objects.get(id=jobpost_id)
        context["jobpost"] = self.jobpost
        return context

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        jobpost_id = self.kwargs.get("pk")
        self.jobpost = models.JobPostModel.objects.get(id=jobpost_id)
        appliedjob = models.AppliedModel.objects.filter(jobpost__id=jobpost_id)
        if not appliedjob.exists():
            form.instance.user = self.request.user
            form.instance.jobpost = self.jobpost
            return super().form_valid(form)
        return redirect(self.get_success_url())

    def get_success_url(self) -> str:
        jobpost_id = self.kwargs.get("pk")
        appliedjob = models.AppliedModel.objects.filter(jobpost__id=jobpost_id).first()
        return reverse_lazy("core:applied_job_detail", kwargs={"pk": appliedjob.id})


class AppliedJobDetailView(LoginRequiredMixin, views.DetailView):
    template_name = "preview.html"
    model = models.AppliedModel
    context_object_name = "appliedjob"


class AppliedListView(LoginRequiredMixin, views.ListView):
    template_name = "applied_list.html"
    model = models.AppliedModel
    context_object_name = "appliedjobs"

    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset()
        employer = getattr(self.request.user, "employermodel", False)
        jobseeker = getattr(self.request.user, "jobseekermodel", False)
        if employer:
            jobposts = employer.jobposts.values_list("id", flat=True)
            qs = qs.filter(jobpost__id__in=jobposts)
        elif jobseeker:
            qs = qs.filter(user=self.request.user)

        return qs


class MyAppliedListView(views.ListView):
    template_name = "myapplied_list.html"
    model = models.AppliedModel
    context_object_name = "appliedjobs"


# class Register(views.CreateView):
#       template_name = "core/register.html"
# model = models.JobseekerModel
# form_class = forms.JobseekerForm
#       success_url = reverse_lazy("core:home")


# class LoginView(auth_views.LoginView):
#  template_name = "registration/login.html"
# redirect_authenticated_user = True

templates/partials/footer.html
<footer class="bg-info mt-3">
    <div class="container-lg">
      <div class="row row-cols-3 g-3">
        <div class="col"></div>
        <div class="col"></div>
        <div class="col"></div>
      </div>
      <div class="row">
        <div class="col">
          <p>All Rights Are Reserved &copy; 2023</p>
        </div>
      </div>
    </div>
  </footer>

templates/partials/n.html
<nav class="navbar navbar-expand-lg bg-info">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Dream Catcher</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'core:home' %}"
            >Home</a
          >
          {% if user.is_authenticated %} 
          {% if user.profilemodel.id %}
          <a
            class="nav-link"
            href="{% url 'accounts:profile_detail' user.profilemodel.id %}"
            >{{user}}</a
          >
          {% else %}
          <a class="nav-link" href="{% url 'accounts:profile_create' %}"
            >{{user}}</a
          >
          {% endif %}
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'accounts:logout' %}"
            >Logout</a
          >
          {% else %}
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'accounts:login' %}"
            >Login</a
          >
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'accounts:signup' %}"
            >Register</a
          >
          {% endif %}
  
          <a class="nav-link" href="#"></a>
          <a class="nav-link" href="#"></a>
          <a class="nav-link disabled"></a>
        </div>
      </div>
    </div>
  </nav>

templates/partials/nav.html
<nav class="navbar navbar-expand-lg bg-info">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Dream Catcher</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a
          class="nav-link active"
          aria-current="page"
          href="{% url 'core:home' %}"
          >Home</a
        >
       
      
        {% if user.is_authenticated and not user.is_superuser %}
        <li class="nav-item dropdown">
          
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Profile</a>
            <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'accounts:profile' %}"
                >For Employer</a >
            </li>
          <li>
              <a class="dropdown-item" href="{% url 'accounts:profile_create' %}"
                >For user</a >
            </li>
            </ul>
        </li>

        
        {% endif %}
        
        {% if user.is_authenticated %} 
        {% if user.is_superuser %}
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {{user}}
          </a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'accounts:create' %}"
                >Add employer</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'accounts:employer_list' %}">Show employer</a
              >
            </li>
          </ul>
        </li>
        
        {% if user.profilemodel.id or user.employermodel.id %}

        {% elif user.employermodel %}
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {{user}}
          </a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'core:jobpost' %}"
                >Add new Job Post</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'core:jobpost_list' %}">Show Job Posts</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'core:jobpost_list' %}">View Applicant</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change Password</a
              >
            </li>
          </ul>
        </li>
        

        {% elif user.profilemodel %}
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {{user}}
          </a>
          <ul class="dropdown-menu">
            
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'core:applied_job_detail' appliedmodel.id %}">View Applied</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change Password</a
              >
            </li>
          </ul>
        </li>
        <form action="{% url 'core:search' %}" class="d-flex" method="get" role="search">
          <input class="form-control me-2" type="search" name="keyword" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

        
{% endif %}
{% endif %}
<a
  class="nav-link active"
  aria-current="page"
  href="{% url 'accounts:logout' %}"
  >Logout</a
>
{% else %}
<a
  class="nav-link active"
  aria-current="page"
  href="{% url 'accounts:login' %}"
  >Login</a
>
<a
  class="nav-link active"
  aria-current="page"
  href="{% url 'accounts:signup' %}"
  >Register</a
>
{% endif %}




        <a class="nav-link" href="#"></a>
        <a class="nav-link" href="#"></a>
        <a class="nav-link disabled"></a>
      </div>
    </div>
  </div>
</nav>

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg bg-info">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'core:home' %}">JOB PORTAL</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav w-100">
        <a
          class="nav-link active"
          aria-current="page"
          href="{% url 'core:home' %}"
          >Home</a
        >
        <!--  -->
        {% if user.is_authenticated %}
        <!--  -->
        {% if user.is_superuser %}

        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {{user}}
          </a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'accounts:create' %}"
                >Add employer</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'accounts:employer_list' %}"
                >Show employer</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'core:jobpost_list' %}"
                >Show Job Posts</a
              >
            </li>
          </ul>
        </li>

        {% elif user.employermodel %}
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {{user}}
          </a>
          <ul class="dropdown-menu">
            <li>
              <a
                class="dropdown-item"
                href="{% url 'accounts:employer_profile_detail' user.employermodel.id %}"
                >My Profile</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'core:jobpost_create' %}"
                >Add new Job Post</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'core:jobpost_list' %}"
                >Show Job Posts</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'core:applied_job_list' %}"
                >View Applications</a
              >
            </li>
            <li>
              <a
                class="dropdown-item"
                href="{% url 'accounts:password_change' %}"
                >Change Password</a
              >
            </li>
          </ul>
        </li>

        {% elif user.jobseekermodel %}
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {{user}}
          </a>
          <ul class="dropdown-menu">
            {% if user.jobseekermodel.profile %}
            <li>
              <a
                class="dropdown-item"
                aria-current="page"
                href="{% url 'accounts:profile_detail' user.jobseekermodel.id %}"
                >View my profile</a
              >
            </li>
            {% else %}
            <li>
              <a
                class="dropdown-item"
                aria-current="page"
                href="{% url 'accounts:profile_create' %}"
                >Create new profile</a
              >
            </li>
            {% endif %}
            <li>
              <a class="dropdown-item" href="{% url 'core:applied_job_list' %}"
                >View my applied jobs</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'core:jobpost_list' %}"
                >Show all job posts</a
              >
            </li>
            <li>
              <a
                class="dropdown-item"
                href="{% url 'accounts:password_change' %}"
                >Change password</a
              >
            </li>
          </ul>
        </li>

        {% endif %}
        <!--  -->

        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'accounts:logout' %}"
            >Logout</a
          >
        </li>

        {% else %}
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'accounts:login' %}"
            >Login</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'accounts:signup' %}"
            >Register</a
          >
        </li>
        {% endif %}
        <li class="nav-item ms-auto me-0">
          <form
            action="{% url 'core:search' %}"
            class="d-flex"
            method="get"
            role="search"
          >
            <div class="input-group">
              <input
                class="form-control"
                type="search"
                name="keyword"
                placeholder="Search"
                aria-label="Search"
              />
              <button class="btn btn-outline-dark" type="submit">Search</button>
            </div>
          </form>
        </li>
      </div>
    </div>
  </div>
</nav>

templates/partials/navbar_a.html
<nav class="navbar navbar-expand-lg bg-info">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Dream Catcher</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:create' %}">Add Employer</a>
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:employer_list' %}">Show Employers</a>
          <a class="nav-link active" aria-current="page" href="#">Search Employer</a>
          <a class="nav-link active" aria-current="page" href="#">View User</a>
          <a class="nav-link active" aria-current="page" href="#">Search User</a>
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">Logout</a>
          <a class="nav-link" href="#"></a>
          <a class="nav-link" href="#"></a>
          <a class="nav-link disabled"></a>
        </div>
      </div>
    </div>
  </nav>

templates/partials/navbar_e.html
<nav class="navbar navbar-expand-lg bg-info">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Dream Catcher</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">

          <a class="nav-link active" aria-current="page" href="{% url 'accounts:profile' %}">Profile</a>
          
          
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              Job Post
            </a>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item" href="{% url 'core:jobpost' %}"
                  >Add new Job Post</a
                >
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'core:jobpost_list' %}">Show Job Posts</a
                >
              </li>
            </ul>
          </li>

          <a class="nav-link active" aria-current="page" href="{% url 'accounts:signup' %}">View Applicant</a>
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:password_change' %}">Change Password</a>
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">Logout</a>
          <a class="nav-link" href="#"></a>
          <a class="nav-link" href="#"></a>
          <a class="nav-link disabled"></a>
        </div>
      </div>
    </div>
  </nav>

templates/partials/navbar_u.html
<nav class="navbar navbar-expand-lg bg-info">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Dream Catcher</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a
          class="nav-link active"
          aria-current="page"
          href="{% url 'accounts:profile_detail' user.profilemodel.id %}"
          >Profile</a
        >
        <a class="nav-link active" aria-current="page" href="#">Search</a>
        <a class="nav-link active" aria-current="page" href="#">View Applied</a>

        <a
          class="nav-link active"
          aria-current="page"
          href="{% url 'accounts:password_change' %}"
          >Change Password</a
        >
        <a
          class="nav-link active"
          aria-current="page"
          href="{% url 'accounts:logout' %}"
          >Logout</a
        >
        <a class="nav-link" href="#"></a>
        <a class="nav-link" href="#"></a>
        <a class="nav-link disabled"></a>
      </div>
    </div>
  </div>
</nav>