accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path,include
from accounts import views

app_name = "accounts"

urlpatterns = [
    
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    
    path("password_change/",views.PasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/",views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    path("password_reset/",views.PasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/",views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/",views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/",views.PasswordResetComleteView.as_view(), name="password_reset_complete"),

 
    path("profile/create/", views.ProfileCreateView.as_view(), name="profile_create"),
    path("profile/<int:pk>/", views.ProfileDetailView.as_view(), name="profile_detail"),
    path("profile/<int:pk>/update/", views.ProfileUpdateView.as_view(), name="profile_update"),
    path("employer/profile/create/", views.EmpprofileCreateView.as_view(), name="profile"),
    path("employer/profile/<int:pk>/", views.EmployerProfileDetailView.as_view(), name="employer_profile_detail"),
    path("employer/profile/<int:pk>/update/", views.EmployerProfileUpdateView.as_view(), name="employer_profile_update"),
    path("add/", views.AddEmployerView.as_view(), name="create"),

    #path("dashboard/", views.DashboardView.as_view(), name="dashboard"),

    #employers
    path("employers/", views.EmployerListView.as_view(), name="employer_list"),
    path("employers/<int:pk>/detail/", views.EmployerDetailView.as_view(), name="employer_detail"),
    path("employers/<int:pk>/update/", views.EmployerUpdateView.as_view(), name="employer_update"),
    path("employers/<int:pk>/delete/", views.EmployerDeleteView.as_view(), name="employer_delete"),

    ]

core/urls.py
from django.urls import path
from core import views

app_name = "core"
urlpatterns = [
    path("", views.HomeView.as_view(),name="home"),
    path("adminhome/", views.AdminHomeView.as_view(),name="ahome"),
    path("emprhome/", views.EmployerHomeView.as_view(),name="ehome"),
    path("userhome/", views.UserHomeView.as_view(),name="uhome"),
    path("search/", views.SearchView.as_view(),name="search"),
    #jobpost

    path("jobpost/create/", views.JobPostCreateView.as_view(), name="jobpost_create"),
    path("jobposts/list/", views.JobpostListView.as_view(), name="jobpost_list"),
    path("jobposts/list/?category=<int:pk>", views.JobpostListByCategoryView.as_view(), name="jobpost_list_by_category"),
    path("jobposts/<int:pk>/detail/", views.JobpostDetailView.as_view(), name="jobpost_detail"),
    path("jobposts/<int:pk>/update/", views.JobpostUpdateView.as_view(), name="jobpost_update"),
    path("jobposts/<int:pk>/delete/", views.JobpostDeleteView.as_view(), name="jobpost_delete"),
    path("jobposts/<int:pk>/detail/", views.DetailView.as_view(), name="more"),
    path("jobposts/<int:pk>/apply/", views.AppliedJobCreateView.as_view(), name="jobpost_apply"),

    # Applied job
    path("applied-job/<int:pk>/", views.AppliedJobDetailView.as_view(), name="applied_job_detail"),
    path("applied-job/list/", views.AppliedListView.as_view(), name="applied_job_list"),
    path("myapplied/list/", views.MyAppliedListView.as_view(), name="myapplied_list"),

   
   # path("login/", views.LoginView.as_view(), name="login"),
   # path("register/", views.LoginView.as_view(), name="register"),
]

dream_catcher/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls',namespace="core")),
    path("accounts/", include("accounts.urls", namespace="accounts")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
import datetime
from typing import Any, Iterable, List

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import QuerySet
from django.db.models.manager import BaseManager
from django.urls import reverse


class TimestampedModel(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class BaseUserModel(TimestampedModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        abstract = True


class QualificationModel(TimestampedModel):
    name = models.CharField(max_length=64)
    course_name = models.CharField(max_length=64)
    description = models.TextField(max_length=500)

    def __str__(self):
        return f"{self.name}. {self.course_name}"


# user profile
class ProfileModel(models.Model):
    def current_year_validator(value):
        if value > datetime.date.today().year:
            raise ValidationError("Year cannot be in the future.")

    class GenderChoices(models.TextChoices):
        MALE = "M", "Male"
        FEMALE = "F", "Female"
        TRANSGENDER = "T", "Transgender"

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    address = models.TextField(max_length=150)
    contact_no = models.BigIntegerField()
    date_of_birth = models.DateField()
    gender = models.CharField(max_length=2, choices=GenderChoices.choices)
    qualification = models.ForeignKey(
        QualificationModel, on_delete=models.SET_NULL, blank=True, null=True
    )
    institution = models.CharField(max_length=64)
    year_of_passing = models.IntegerField(
        validators=[
            MinValueValidator(2010),  # Change the minimum value as needed
            current_year_validator,  # Change the maximum value as needed
        ]
    )
    percentage = models.DecimalField(decimal_places=2, max_digits=5)
    experience = models.DecimalField(decimal_places=2, max_digits=5)
    skills = models.TextField(max_length=150, blank=True, null=True)
    resume = models.FileField(
        upload_to="accounts/profile/resumes/", blank=True, null=True
    )
    image = models.ImageField(
        upload_to="accounts/profile/image/",
        default="default/user.png",
    )
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("accounts:profile_detail", args=(self.pk,))


# employer profile
class EmployerModel(models.Model):
    company_name = models.CharField(max_length=64)
    address = models.TextField(max_length=150)
    contact_no = models.CharField(max_length=15, blank=True, null=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse("accounts:profile_detail", args=(self.pk,))

    def __str__(self) -> str:
        return self.company_name or "Not Defined"

    @property
    def jobposts(self) -> BaseManager[Any]:
        posts = getattr(self.user, "jobposts", QuerySet())
        return posts


class JobSeekerModel(BaseUserModel):
    profile = models.OneToOneField(
        ProfileModel, on_delete=models.SET_NULL, blank=True, null=True
    )

    def __str__(self) -> str:
        return f"{self.user.username}"

accounts/forms.py
from typing import Any
from django import forms
from accounts import models
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class ProfileForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))

    class Meta:
        model = models.ProfileModel
        exclude = ("user", "status")


class EmployerProfileForm(forms.ModelForm):
    class Meta:
        model = models.EmployerModel
        exclude = ("user", "status")


class UserForm(UserCreationForm):
    is_employer = forms.BooleanField(label="Are you an Emloyer?", required=False)

    class Meta:
        model = get_user_model()
        fields = ["email", "username", "password1", "password2"]

    def save(self, commit=True):
        user = super().save(commit)
        is_employer = self.cleaned_data["is_employer"]
        if is_employer:
            employer = models.EmployerModel.objects.create(user=user)
        else:
            jobseeker = models.JobSeekerModel.objects.create(user=user)
        return user

accounts/views.py
from typing import Any, Optional
from django.contrib.auth.forms import AuthenticationForm
from django.db.models.query import QuerySet
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import models
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic as views

from accounts import forms, models


class ProfileCreateView(LoginRequiredMixin, views.CreateView):
    template_name = "accounts/profile/profile_create.html"
    model = models.ProfileModel
    form_class = forms.ProfileForm
    login_url = reverse_lazy("accounts:login")
    context_object_name = "profile"
    extra_context = {
        "project_name": "Dream_Catcher",
        "page_name": "user profile create",
    }

    def form_valid(self, form):
        response = super().form_valid(form)
        jobseeker: models.JobSeekerModel | False = getattr(
            self.request.user, "jobseekermodel", False
        )

        if jobseeker:
            profile_exists: models.ProfileModel = getattr(jobseeker, "profile", False)
            if not profile_exists:
                jobseeker.profile = self.object
                jobseeker.save()

        return response


class ProfileDetailView(LoginRequiredMixin, views.DetailView):
    template_name = "accounts/profile/profile_detail.html"
    model = models.ProfileModel
    context_object_name = "profile"


class ProfileUpdateView(LoginRequiredMixin, views.UpdateView):
    template_name = "accounts/profile/profile_update.html"
    model = models.ProfileModel
    context_object_name = "profile"
    form_class = forms.ProfileForm


class EmpprofileCreateView(LoginRequiredMixin, views.CreateView):
    template_name = "accounts/profile/empr_profile.html"
    model = models.EmployerModel
    form_class = forms.EmployerProfileForm
    login_url = reverse_lazy("accounts:login")
    context_object_name = "employer"
    extra_context = {
        "project_name": "Dream_Catcher",
        "page_name": "Employer profile create",
    }

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class EmployerProfileDetailView(LoginRequiredMixin, views.DetailView):
    template_name = "accounts/profile/employer_profile_detail.html"
    model = models.EmployerModel
    context_object_name = "employer"


class EmployerProfileUpdateView(LoginRequiredMixin, views.UpdateView):
    template_name = "accounts/profile/employer_profile_update.html"
    model = models.EmployerModel
    context_object_name = "employer"
    form_class = forms.EmployerProfileForm

    def get_success_url(self) -> str:
        return reverse_lazy(
            "accounts:employer_profile_detail", kwargs={"pk": self.object.id}
        )


# Authentication
class LoginView(auth_views.LoginView):
    template_name = "registration/login.html"
    redirect_authenticated_user = True
    extra_context = {
        "project_name": "Dream_Catcher",
        "page_name": "Login",
    }

    def form_valid(self, form: AuthenticationForm) -> HttpResponse:
        response = super().form_valid(form)
        if hasattr(self.request.user, "jobseekermodel"):
            return redirect(reverse_lazy("core:home"))
        return response


class LogoutView(auth_views.LogoutView):
    template_name = "registration/logout.html"
    success_url = reverse_lazy("core:home")


class PasswordChangeView(auth_views.PasswordChangeView):
    template_name = "registration/password_change_form.html"
    success_url = reverse_lazy("accounts:password_change_done")


class PasswordChangeDoneView(auth_views.PasswordChangeDoneView):
    template_name = "registration/password_change_form.html"
    success_url = reverse_lazy("accounts:password_change_done")


class PasswordResetView(auth_views.PasswordResetView):
    template_name = "registration/password_reset_form.html"
    success_url = reverse_lazy("accounts:password_reset_done")


class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = "registration/password_reset_done.html"


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = "registration/password_reset_confirm.html"
    success_url = reverse_lazy("accounts:password_reset_complete")


class PasswordResetComleteView(auth_views.PasswordResetCompleteView):
    template_name = "registration/password_reset_complete.html"


# User Registration
class SignupView(views.CreateView):
    template_name = "registration/signup.html"
    form_class = forms.UserForm
    success_url = reverse_lazy("accounts:login")


class AddEmployerView(views.CreateView):
    template_name = "registration/add_employer.html"
    model = models.EmployerModel
    form_class = forms.UserForm
    success_url = reverse_lazy("accounts:login")
    context_object_name = "employer"


class EmployerListView(views.ListView):
    template_name = "accounts/employer/employer_list.html"
    model = models.EmployerModel
    context_object_name = "employer"


class EmployerDetailView(views.DetailView):
    template_name = "accounts/employer/employer_detail.html"
    model = models.EmployerModel
    context_object_name = "employer"


class EmployerUpdateView(views.UpdateView):
    template_name = "accounts/employer/employer_update.html"
    model = models.EmployerModel
    form_class = forms.UserForm
    success_url = reverse_lazy("accounts:employer_list")


class EmployerDeleteView(views.DeleteView):
    template_name = "accounts/employer/employer_delete.html"
    model = models.EmployerModel
    success_url = reverse_lazy("accounts:employer_list")
    context_object_name = "employer"


class DashboardView(LoginRequiredMixin, views.TemplateView):
    template_name = "accounts/dashboard.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        user = self.request.user
        actions = []
        if hasattr(user, "jobseekermodel"):
            actions = ["My Jobs", "Notifications", "Profile Settings"]
            # here you can add custom data the above action is for an example
        elif user.is_superuser:
            actions = [""]

        elif hasattr(user, "employermodel"):
            actions = ["Post Jobs"]
        context.update({"actions": actions})
        return context

templates/accounts/employer/employer_delete.html
{% extends 'base.html' %} {% block content %}
<div class="container-lg d-flex flex-column gap-3 py-3">
  <div class="row">
    <div class="col">
      <h1>Employer Delete</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Delete Employer?</h4>
        </div>
        <div class="card-body">
          <p class="card-text">Are you sure want to delete?</p>
          <p>"{{employer}}"</p>
        </div>
        <div class="card-footer">
          <form action="" method="post">
            {% csrf_token %}
            <div class="d-flex gap-3">
              <a
                href="{% url 'accounts:employer_detail' employer.id %}"
                class="btn btn-secondary"
                >Cancel</a
              >
              <button type="submit" class="btn btn-danger">Delete</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>




<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

{% endblock %}

templates/accounts/employer/employer_detail.html
{% extends 'base.html' %} {% block content %}
<div class="container-lg d-flex flex-column gap-3 py-3">
  <div class="row">
    <div class="col">
      <h1>Employer Details</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <table class="table table-bordered align-middle shadow-sm">
        <thead>
          <tr>
            <th class="text-center">Field</th>
            <th>Data</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>ID</td>
            <td>{{employer.id}}</td>
          </tr>
          <tr>
            <td>Company Name</td>
            <td>{{employer.company_name}}</td>
          </tr>
          <tr>
            <td>Address</td>
            <td>{{employer.address}}</td>
          </tr>
          <tr>
            <td>Contact No</td>
            <td>{{employer.contact_no}}</td>
          </tr>
          
          <tr>
            <th>Actions</th>
            <td>
              <div class="d-flex gap-3 flex-wrap">
                
                <a
                  href="{% url 'accounts:employer_delete' employer.id %}"
                  class="btn btn-danger"
                  >Delete</a
                >
              </div>
              


            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>


<br>
<br>
<br>
<br>
<br>
<br>
<br>

{% endblock %}

templates/accounts/employer/employer_list.html
{% extends 'base.html' %} {% block content %}
<div class="container-lg d-flex flex-column gap-3 py-3">
  <div class="row">
    <div class="col">
      <h1>List of Employers</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <table class="table table-bordered align-middle shadow-sm">
        <thead>
          <tr>
            <th class="text-center">#</th>
            <th>Company Name</th>
            
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for employer in employer %}
          <tr>
            <td class="text-center">{{forloop.counter}}</td>
            <td>{{employer}}</td>
            
            
            <td>
              <div class="d-flex gap-3 flex-wrap">
                <a
                  href="{% url 'accounts:employer_detail' employer.id %}"
                  class="btn btn-primary"
                  >Detail</a
                >
                
                <a
                  href="{% url 'accounts:employer_delete' employer.id %}"
                  class="btn btn-danger"
                  >Delete</a
                >
              </div>
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="5">No Employer Found!</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>




{% endblock %}

templates/accounts/employer/employer_update.html
{% extends 'base.html' %} {% block content %}
<div class="container-lg d-flex flex-column gap-3 py-3">
  <div class="row">
    <div class="col">
      <h1>Add Employer</h1>
    </div>
  </div>
  <div class="row">
    
    <div class="col">
      <div class="card card-body">
        <form action="" method="post" class="django-form">
          {% csrf_token %} {{form.as_p}}
          
          <button class="btn btn-primary" type="submit">Update</button>
        </form>
      </div>
    </div>
  </div>
</div>


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

{% endblock %}