core/urls.py
from django.urls import path
from core import views

app_name = "core"
urlpatterns = [
    path("", views.HomeView.as_view(),name="home"),
    path("adminhome/", views.AdminHomeView.as_view(),name="ahome"),
    path("emprhome/", views.EmployerHomeView.as_view(),name="ehome"),
    path("userhome/", views.UserHomeView.as_view(),name="uhome"),
    path("search/", views.SearchView.as_view(),name="search"),
    #jobpost

    path("jobpost/create/", views.JobPostCreateView.as_view(), name="jobpost_create"),
    path("jobposts/list/", views.JobpostListView.as_view(), name="jobpost_list"),
    path("jobposts/list/?category=<int:pk>", views.JobpostListByCategoryView.as_view(), name="jobpost_list_by_category"),
    path("jobposts/<int:pk>/detail/", views.JobpostDetailView.as_view(), name="jobpost_detail"),
    path("jobposts/<int:pk>/update/", views.JobpostUpdateView.as_view(), name="jobpost_update"),
    path("jobposts/<int:pk>/delete/", views.JobpostDeleteView.as_view(), name="jobpost_delete"),
    path("jobposts/<int:pk>/detail/", views.DetailView.as_view(), name="more"),
    path("jobposts/<int:pk>/apply/", views.AppliedJobCreateView.as_view(), name="jobpost_apply"),

    # Applied job
    path("applied-job/<int:pk>/", views.AppliedJobDetailView.as_view(), name="applied_job_detail"),
    path("applied-job/list/", views.AppliedListView.as_view(), name="applied_job_list"),
    path("myapplied/list/", views.MyAppliedListView.as_view(), name="myapplied_list"),

   
   # path("login/", views.LoginView.as_view(), name="login"),
   # path("register/", views.LoginView.as_view(), name="register"),
]

dream_catcher/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls',namespace="core")),
    path("accounts/", include("accounts.urls", namespace="accounts")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.conf import settings
from django.db import models

from accounts.models import EmployerModel

# Create your models here.
# class login(models.Model):
#  Email = models.EmailField(max_length=64)


# class Register(models.Model):
#   Name = models.CharField(max_length=64)
#   Email = models.CharField(max_length=64)
#   Password = models.TextField(max_length=500)
# contact_no = models.(max_length=500)


# category model


class Category(models.Model):
    name = models.CharField(max_length=64)
    no_of_vacancy = models.IntegerField()
    image = models.ImageField(
        upload_to="core/category/image/", default="default/logo.png"
    )
    parent = models.ForeignKey("self", on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self) -> str:
        return self.name


class JobPostModel(models.Model):
    class CatChoices(models.TextChoices):
        Accounting = "Accounting", "Accounting"
        administrative_assistant = "admini", "Administrative Assistant"
        architect = "architect", "Architect"
        computer_programmer = "cp", "Computer Programmer"
        Construction = "con", "Construction"
        Customer_service = "cs", "Ustomer Service"
        dbadministrator = "dbadmini", "Database Administrator"
        HR = "hr", "Human Resources"
        marketing = "marketing", "Marketing"
        retail = "retail", "Retail"
        sales = "sales", "Sales"

    class QualificationChoices(models.TextChoices):
        Phd = "phd", "PhD"
        PG = "PG", "Post Graduate"
        UG = "UG", "Under Graduate"
        Diploma = "Dip", "Diploma"
        X = "X", "SSLC"

    class EmploymentTypeChoices(models.TextChoices):
        Full_time = "full", "Full Time"
        Part_time = "part", "Part Time"

    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, blank=True, null=True
    )
    post_name = models.CharField(max_length=64)
    company_name = models.CharField(max_length=64)
    qualification = models.CharField(
        max_length=64, choices=QualificationChoices.choices
    )
    skills = models.TextField(max_length=60)
    experience = models.FloatField()
    no_of_vacancy = models.IntegerField()
    location = models.CharField(max_length=255)
    salary = models.FloatField()
    employment_type = models.CharField(
        max_length=64, choices=EmploymentTypeChoices.choices
    )
    last_date = models.DateField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    posted_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="jobposts",
        blank=True,
    )

    def __str__(self) -> str:
        return self.post_name

    @property
    def employer(self) -> EmployerModel:
        employer = EmployerModel.objects.get(user=self.posted_by)
        return employer


#
class AppliedModel(models.Model):
    jobpost = models.ForeignKey(
        JobPostModel, on_delete=models.CASCADE, blank=True, null=True
    )
    resume = models.FileField(upload_to="core/applied/resumes/", blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.jobpost)

core/forms.py
import datetime
from django import forms
from core import models


# class RegisterForm(forms.ModelForm):
#   class Meta:
#       model = models.Register
#      fields = ["Name","Email","Password"]


class JobPostForm(forms.ModelForm):
    last_date = forms.DateField(
        widget=forms.DateInput(
            attrs={"type": "date", "min": str(datetime.date.today())}
        )
    )
    company_name = forms.CharField(widget=forms.TextInput(attrs={"readonly": True}))

    class Meta:
        model = models.JobPostModel
        fields = [
            "category",
            "post_name",
            "company_name",
            "qualification",
            "skills",
            "experience",
            "no_of_vacancy",
            "location",
            "salary",
            "employment_type",
            "last_date",
        ]


class AppliedForm(forms.ModelForm):
    class Meta:
        model = models.AppliedModel
        fields = ["resume"]

core/views.py
from typing import Any, Dict

from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic as views

from core import forms, models

# from accounts import forms, models
category = [
    {
        "name": "Marketing",
        "no of vacancy": "20",
        "image": "/media/default/logo.png",
    },
    {
        "name": "Customer Service",
        "no_of_vacancy": "20",
        "image": "/media/default/logo.png",
    },
    {
        "name": "HR",
        "no_of_vacancy": "20",
        "image": "/media/default/logo.png",
    },
    {
        "name": "Project Management",
        "no_of_vacancy": "20",
        "image": "/media/default/logo.png",
    },
]

common_data = {
    "project_name": "Dream_Catcher",
    "page_name": "Home",
}


class HomeView(views.TemplateView):
    template_name = "core/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        catergories = models.Category.objects.all()
        context["categories"] = catergories
        context.update(common_data)
        return context


class SearchView(views.TemplateView):
    template_name = "search.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        kw = self.request.GET["keyword"]
        result = models.JobPostModel.objects.filter(post_name__icontains=kw)
        print(result)
        context["results"] = result

        return context


class AdminHomeView(LoginRequiredMixin, PermissionRequiredMixin, views.TemplateView):
    template_name = "core/admin_home.html"
    extra_context = {
        "project_name": "Dream_Catcher",
        "page_name": "Admin Home",
    }
    permission_required = []
    permission_denied_message = "You are not allowed to view this page"

    def has_permission(self) -> bool:
        permitted = self.request.user.is_superuser and super().has_permission()
        return permitted


class EmployerHomeView(views.TemplateView):
    template_name = "core/empr_home.html"
    extra_context = {
        "project_name": "Dream_Catcher",
        "page_name": "employer Home",
    }


class UserHomeView(views.TemplateView):
    template_name = "core/user_home.html"
    extra_context = {
        "project_name": "Dream_Catcher",
        "page_name": "User Home",
    }


class JobPostCreateView(LoginRequiredMixin, views.CreateView):
    template_name = "core/jobpost/jobpost_create.html"
    model = models.JobPostModel
    form_class = forms.JobPostForm
    success_url = reverse_lazy("core:jobpost_list")
    context_object_name = "jobpost"

    def get_form_kwargs(self) -> Dict[str, Any]:
        kwargs = super().get_form_kwargs()
        if hasattr(self.request.user, "employermodel"):
            kwargs.update(
                {
                    "initial": {
                        "company_name": self.request.user.employermodel.company_name,
                    }
                }
            )
        return kwargs

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.posted_by = self.request.user
        return super().form_valid(form)


class JobpostListView(views.ListView):
    template_name = "core/jobpost/jobpost_list.html"
    model = models.JobPostModel
    context_object_name = "jobposts"

    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset()

        employer = getattr(self.request.user, "employermodel", False)
        if employer:
            qs = qs.filter(posted_by=self.request.user)

        return qs


class JobpostDetailView(views.DetailView):
    template_name = "core/jobpost/jobpost_detail.html"
    model = models.JobPostModel
    context_object_name = "jobpost"


class JobpostUpdateView(views.UpdateView):
    template_name = "core/jobpost/jobpost_update.html"
    model = models.JobPostModel
    form_class = forms.JobPostForm
    success_url = reverse_lazy("core:jobpost_list")


class JobpostDeleteView(views.DeleteView):
    template_name = "core/jobpost/jobpost_delete.html"
    model = models.JobPostModel
    success_url = reverse_lazy("core:jobpost_list")
    context_object_name = "jobpost"


class JobpostListByCategoryView(views.ListView):
    template_name = "core/jobpost/jobpost_list.html"
    model = models.JobPostModel
    context_object_name = "jobposts"

    def get_queryset(self) -> QuerySet[Any]:
        q = super().get_queryset()
        q.filter(id=self.kwargs.get("pk"))
        return q


class DetailView(views.DetailView):
    template_name = "details.html"
    model = models.JobPostModel
    context_object_name = "jobpost"


class AppliedJobCreateView(LoginRequiredMixin, views.CreateView):
    template_name = "applied.html"
    model = models.AppliedModel
    form_class = forms.AppliedForm
    context_object_name = "jobpost"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        jobpost_id = self.kwargs.get("pk")
        self.jobpost = models.JobPostModel.objects.get(id=jobpost_id)
        context["jobpost"] = self.jobpost
        return context

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        jobpost_id = self.kwargs.get("pk")
        self.jobpost = models.JobPostModel.objects.get(id=jobpost_id)
        appliedjob = models.AppliedModel.objects.filter(jobpost__id=jobpost_id)
        if not appliedjob.exists():
            form.instance.user = self.request.user
            form.instance.jobpost = self.jobpost
            return super().form_valid(form)
        return redirect(self.get_success_url())

    def get_success_url(self) -> str:
        jobpost_id = self.kwargs.get("pk")
        appliedjob = models.AppliedModel.objects.filter(jobpost__id=jobpost_id).first()
        return reverse_lazy("core:applied_job_detail", kwargs={"pk": appliedjob.id})


class AppliedJobDetailView(LoginRequiredMixin, views.DetailView):
    template_name = "preview.html"
    model = models.AppliedModel
    context_object_name = "appliedjob"


class AppliedListView(LoginRequiredMixin, views.ListView):
    template_name = "applied_list.html"
    model = models.AppliedModel
    context_object_name = "appliedjobs"

    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset()
        employer = getattr(self.request.user, "employermodel", False)
        jobseeker = getattr(self.request.user, "jobseekermodel", False)
        if employer:
            jobposts = employer.jobposts.values_list("id", flat=True)
            qs = qs.filter(jobpost__id__in=jobposts)
        elif jobseeker:
            qs = qs.filter(user=self.request.user)

        return qs


class MyAppliedListView(views.ListView):
    template_name = "myapplied_list.html"
    model = models.AppliedModel
    context_object_name = "appliedjobs"


# class Register(views.CreateView):
#       template_name = "core/register.html"
# model = models.JobseekerModel
# form_class = forms.JobseekerForm
#       success_url = reverse_lazy("core:home")


# class LoginView(auth_views.LoginView):
#  template_name = "registration/login.html"
# redirect_authenticated_user = True

templates/core/jobpost/jobpost_create.html
{% extends 'base.html' %} {% block content %}
<div class="container-lg py-lg-5 py-3 min-vh-100">
  <div class="row">
    <div class="col">
      <h1>Post Job Vacancy</h1>
      <hr />
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card card-body">
        <form action="" method="post" class="django-form">
          {% csrf_token %}
          <table class="table table-borderless">
            {{form.as_table}}
            <tr>
              <td colspan="2">
                <button class="btn btn-primary" type="submit">Save</button>
              </td>
            </tr>
          </table>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/core/jobpost/jobpost_delete.html
{% extends 'base.html' %} {% block content %}
<div class="container-lg d-flex flex-column gap-3 py-3">
  <div class="row">
    <div class="col">
      <h1>Jobpost Delete</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Delete Job Post?</h4>
        </div>
        <div class="card-body">
          <p class="card-text">Are you sure want to delete?</p>
          <p>"{{jobpost}}"</p>
        </div>
        <div class="card-footer">
          <form action="" method="post">
            {% csrf_token %}
            <div class="d-flex gap-3">
              <a
                href="{% url 'core:jobpost_detail' jobpost.id %}"
                class="btn btn-secondary"
                >Cancel</a
              >
              <button type="submit" class="btn btn-danger">Delete</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

{% endblock %}

templates/core/jobpost/jobpost_detail.html
{% extends 'base.html' %} {% block content %}
<div class="container-lg py-lg-5 py-3 min-vh-100">
  <div class="row">
    <div class="col">
      <div class="d-flex align-items-center justify-content-between">
        <h1 class="m-0">Job Post Details</h1>
        <div class="d-flex gap-3 flex-wrap">
          {% if user.is_superuser or user.employermodel and jobpost.posted_by == user %}
          <a
            href="{% url 'core:jobpost_update' jobpost.id %}"
            class="btn btn-info"
            >Edit</a
          >
          <a
            href="{% url 'core:jobpost_delete' jobpost.id %}"
            class="btn btn-danger"
            >Delete</a
          >
          {% elif jobpost.posted_by != user and user.employermodel %}
          <a href="#" class="btn btn-warning disabled"
            >You are not allowed to edit this Jobpost</a
          >
          {% else %}
          <a
            href="{% url 'core:jobpost_apply' jobpost.id %}"
            class="btn btn-primary"
            >Apply</a
          >
          {% endif %}
        </div>
      </div>
      <hr />
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="table-responsive">
        <table class="table table-bordered align-middle">
          <tbody>
            <tr>
              <td>ID</td>
              <td>{{jobpost.id}}</td>
            </tr>
            <tr>
              <td>Category</td>
              <td>{{jobpost.category}}</td>
            </tr>
            <tr>
              <td>Post Name</td>
              <td>{{jobpost.post_name}}</td>
            </tr>
            <tr>
              <td>Qualification</td>
              <td>{{jobpost.qualification}}</td>
            </tr>
            <tr>
              <td>Skills</td>
              <td>{{jobpost.skills}}</td>
            </tr>
            <tr>
              <td>Experience</td>
              <td>{{jobpost.experience}}</td>
            </tr>
            <tr></tr>
            <tr>
              <td>No of Vacancy</td>
              <td>{{jobpost.no_of_vacancy}}</td>
            </tr>

            <tr>
              <td>Location</td>
              <td>{{jobpost.location}}</td>
            </tr>
            <tr>
              <td>Salary</td>
              <td>{{jobpost.salary}}</td>
            </tr>
            <tr>
              <td>Employment Type</td>
              <td>{{jobpost.employment_type}}</td>
            </tr>
            <tr>
              <td>Last Date</td>
              <td>{{jobpost.last_date}}</td>
            </tr>
            <tr>
              <td>Created On</td>
              <td>{{jobpost.created_on}}</td>
            </tr>
            <tr>
              <td>Updated On</td>
              <td>{{jobpost.updated_on}}</td>
            </tr>
            <tr>
              <th>Actions</th>
              <td>
                <div class="d-flex gap-3 flex-wrap">
                  {% if user.is_superuser or user.employermodel and jobpost.posted_by == user %}
                  <a
                    href="{% url 'core:jobpost_update' jobpost.id %}"
                    class="btn btn-info"
                    >Edit</a
                  >
                  <a
                    href="{% url 'core:jobpost_delete' jobpost.id %}"
                    class="btn btn-danger"
                    >Delete</a
                  >
                  {% elif jobpost.posted_by != user and user.employermodel %}
                  <a href="#" class="btn btn-warning disabled"
                    >You are not allowed to edit this Jobpost</a
                  >
                  {% else %}
                  <a
                    href="{% url 'core:jobpost_apply' jobpost.id %}"
                    class="btn btn-primary"
                    >Apply</a
                  >
                  {% endif %}
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/core/jobpost/jobpost_list.html
{% extends 'base.html' %} {% load humanize %} {% block content %}
<div class="container-lg py-lg-5 py-3 min-vh-100">
  <div class="row">
    <div class="col">
      <h1>List of Job Posted</h1>
      <hr />
    </div>
  </div>
  <div class="row">
    <div class="col">
      <table class="table table-bordered align-middle shadow-sm">
        <thead>
          <tr>
            <th class="text-center">#</th>
            <th>Post Name</th>
            <th>Last Updated</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for jobpost in jobposts %}
          <tr>
            <td class="text-center">{{forloop.counter}}</td>
            <td>{{jobpost}}</td>

            <td>{{jobpost.updated_on|naturaltime}}</td>
            <td>
              <div class="d-flex gap-3 flex-wrap">
                {% if user.jobseekermodel %}
                <a
                  href="{% url 'core:jobpost_apply' jobpost.id %}"
                  class="btn btn-primary"
                  >Apply</a
                >
                {% endif %}
                <a
                  href="{% url 'core:jobpost_detail' jobpost.id %}"
                  class="btn btn-secondary"
                  >Detail</a
                >
                {% if user.is_superuser or user.employermodel and jobpost.posted_by == user %}
                <a
                  href="{% url 'core:jobpost_update' jobpost.id %}"
                  class="btn btn-info"
                  >Edit</a
                >
                <a
                  href="{% url 'core:jobpost_delete' jobpost.id %}"
                  class="btn btn-danger"
                  >Delete</a
                >
                {% endif %}
              </div>
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="5">No Job Posted Yet!</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}

templates/core/jobpost/jobpost_update.html
{% extends 'base.html' %} {% block content %}
<div class="container-lg d-flex flex-column gap-3 py-3">
  <div class="row">
    <div class="col">
      <h1>Post Job Vacancy</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card card-body">
        <form action="" method="post" class="django-form">
          {% csrf_token %} {{form.as_p}}
          <button class="btn btn-primary" type="submit">Update</button>
        </form>
      </div>
    </div>
  </div>
</div>



{% endblock %}