accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path,include
from accounts import views

app_name = "accounts"

urlpatterns = [
    
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    
    path("password_change/",views.PasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/",views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    path("password_reset/",views.PasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/",views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/",views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/",views.PasswordResetComleteView.as_view(), name="password_reset_complete"),

 
    path("profile/create/", views.ProfileCreateView.as_view(), name="profile_create"),
    path("profile/<int:pk>/", views.ProfileDetailView.as_view(), name="profile_detail"),
    path("profile/<int:pk>/update/", views.ProfileUpdateView.as_view(), name="profile_update"),
    path("employer/profile/create/", views.EmpprofileCreateView.as_view(), name="profile"),
    path("employer/profile/<int:pk>/", views.EmployerProfileDetailView.as_view(), name="employer_profile_detail"),
    path("employer/profile/<int:pk>/update/", views.EmployerProfileUpdateView.as_view(), name="employer_profile_update"),
    path("add/", views.AddEmployerView.as_view(), name="create"),

    #path("dashboard/", views.DashboardView.as_view(), name="dashboard"),

    #employers
    path("employers/", views.EmployerListView.as_view(), name="employer_list"),
    path("employers/<int:pk>/detail/", views.EmployerDetailView.as_view(), name="employer_detail"),
    path("employers/<int:pk>/update/", views.EmployerUpdateView.as_view(), name="employer_update"),
    path("employers/<int:pk>/delete/", views.EmployerDeleteView.as_view(), name="employer_delete"),

    ]

core/urls.py
from django.urls import path
from core import views

app_name = "core"
urlpatterns = [
    path("", views.HomeView.as_view(),name="home"),
    path("adminhome/", views.AdminHomeView.as_view(),name="ahome"),
    path("emprhome/", views.EmployerHomeView.as_view(),name="ehome"),
    path("userhome/", views.UserHomeView.as_view(),name="uhome"),
    path("search/", views.SearchView.as_view(),name="search"),
    #jobpost

    path("jobpost/create/", views.JobPostCreateView.as_view(), name="jobpost_create"),
    path("jobposts/list/", views.JobpostListView.as_view(), name="jobpost_list"),
    path("jobposts/list/?category=<int:pk>", views.JobpostListByCategoryView.as_view(), name="jobpost_list_by_category"),
    path("jobposts/<int:pk>/detail/", views.JobpostDetailView.as_view(), name="jobpost_detail"),
    path("jobposts/<int:pk>/update/", views.JobpostUpdateView.as_view(), name="jobpost_update"),
    path("jobposts/<int:pk>/delete/", views.JobpostDeleteView.as_view(), name="jobpost_delete"),
    path("jobposts/<int:pk>/detail/", views.DetailView.as_view(), name="more"),
    path("jobposts/<int:pk>/apply/", views.AppliedJobCreateView.as_view(), name="jobpost_apply"),

    # Applied job
    path("applied-job/<int:pk>/", views.AppliedJobDetailView.as_view(), name="applied_job_detail"),
    path("applied-job/list/", views.AppliedListView.as_view(), name="applied_job_list"),
    path("myapplied/list/", views.MyAppliedListView.as_view(), name="myapplied_list"),

   
   # path("login/", views.LoginView.as_view(), name="login"),
   # path("register/", views.LoginView.as_view(), name="register"),
]

dream_catcher/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls',namespace="core")),
    path("accounts/", include("accounts.urls", namespace="accounts")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.conf import settings
from django.db import models

from accounts.models import EmployerModel

# Create your models here.
# class login(models.Model):
#  Email = models.EmailField(max_length=64)


# class Register(models.Model):
#   Name = models.CharField(max_length=64)
#   Email = models.CharField(max_length=64)
#   Password = models.TextField(max_length=500)
# contact_no = models.(max_length=500)


# category model


class Category(models.Model):
    name = models.CharField(max_length=64)
    no_of_vacancy = models.IntegerField()
    image = models.ImageField(
        upload_to="core/category/image/", default="default/logo.png"
    )
    parent = models.ForeignKey("self", on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self) -> str:
        return self.name


class JobPostModel(models.Model):
    class CatChoices(models.TextChoices):
        Accounting = "Accounting", "Accounting"
        administrative_assistant = "admini", "Administrative Assistant"
        architect = "architect", "Architect"
        computer_programmer = "cp", "Computer Programmer"
        Construction = "con", "Construction"
        Customer_service = "cs", "Ustomer Service"
        dbadministrator = "dbadmini", "Database Administrator"
        HR = "hr", "Human Resources"
        marketing = "marketing", "Marketing"
        retail = "retail", "Retail"
        sales = "sales", "Sales"

    class QualificationChoices(models.TextChoices):
        Phd = "phd", "PhD"
        PG = "PG", "Post Graduate"
        UG = "UG", "Under Graduate"
        Diploma = "Dip", "Diploma"
        X = "X", "SSLC"

    class EmploymentTypeChoices(models.TextChoices):
        Full_time = "full", "Full Time"
        Part_time = "part", "Part Time"

    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, blank=True, null=True
    )
    post_name = models.CharField(max_length=64)
    company_name = models.CharField(max_length=64)
    qualification = models.CharField(
        max_length=64, choices=QualificationChoices.choices
    )
    skills = models.TextField(max_length=60)
    experience = models.FloatField()
    no_of_vacancy = models.IntegerField()
    location = models.CharField(max_length=255)
    salary = models.FloatField()
    employment_type = models.CharField(
        max_length=64, choices=EmploymentTypeChoices.choices
    )
    last_date = models.DateField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    posted_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="jobposts",
        blank=True,
    )

    def __str__(self) -> str:
        return self.post_name

    @property
    def employer(self) -> EmployerModel:
        employer = EmployerModel.objects.get(user=self.posted_by)
        return employer


#
class AppliedModel(models.Model):
    jobpost = models.ForeignKey(
        JobPostModel, on_delete=models.CASCADE, blank=True, null=True
    )
    resume = models.FileField(upload_to="core/applied/resumes/", blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.jobpost)

core/forms.py
import datetime
from django import forms
from core import models


# class RegisterForm(forms.ModelForm):
#   class Meta:
#       model = models.Register
#      fields = ["Name","Email","Password"]


class JobPostForm(forms.ModelForm):
    last_date = forms.DateField(
        widget=forms.DateInput(
            attrs={"type": "date", "min": str(datetime.date.today())}
        )
    )
    company_name = forms.CharField(widget=forms.TextInput(attrs={"readonly": True}))

    class Meta:
        model = models.JobPostModel
        fields = [
            "category",
            "post_name",
            "company_name",
            "qualification",
            "skills",
            "experience",
            "no_of_vacancy",
            "location",
            "salary",
            "employment_type",
            "last_date",
        ]


class AppliedForm(forms.ModelForm):
    class Meta:
        model = models.AppliedModel
        fields = ["resume"]

core/views.py
from typing import Any, Dict

from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic as views

from core import forms, models

# from accounts import forms, models
category = [
    {
        "name": "Marketing",
        "no of vacancy": "20",
        "image": "/media/default/logo.png",
    },
    {
        "name": "Customer Service",
        "no_of_vacancy": "20",
        "image": "/media/default/logo.png",
    },
    {
        "name": "HR",
        "no_of_vacancy": "20",
        "image": "/media/default/logo.png",
    },
    {
        "name": "Project Management",
        "no_of_vacancy": "20",
        "image": "/media/default/logo.png",
    },
]

common_data = {
    "project_name": "Dream_Catcher",
    "page_name": "Home",
}


class HomeView(views.TemplateView):
    template_name = "core/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        catergories = models.Category.objects.all()
        context["categories"] = catergories
        context.update(common_data)
        return context


class SearchView(views.TemplateView):
    template_name = "search.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        kw = self.request.GET["keyword"]
        result = models.JobPostModel.objects.filter(post_name__icontains=kw)
        print(result)
        context["results"] = result

        return context


class AdminHomeView(LoginRequiredMixin, PermissionRequiredMixin, views.TemplateView):
    template_name = "core/admin_home.html"
    extra_context = {
        "project_name": "Dream_Catcher",
        "page_name": "Admin Home",
    }
    permission_required = []
    permission_denied_message = "You are not allowed to view this page"

    def has_permission(self) -> bool:
        permitted = self.request.user.is_superuser and super().has_permission()
        return permitted


class EmployerHomeView(views.TemplateView):
    template_name = "core/empr_home.html"
    extra_context = {
        "project_name": "Dream_Catcher",
        "page_name": "employer Home",
    }


class UserHomeView(views.TemplateView):
    template_name = "core/user_home.html"
    extra_context = {
        "project_name": "Dream_Catcher",
        "page_name": "User Home",
    }


class JobPostCreateView(LoginRequiredMixin, views.CreateView):
    template_name = "core/jobpost/jobpost_create.html"
    model = models.JobPostModel
    form_class = forms.JobPostForm
    success_url = reverse_lazy("core:jobpost_list")
    context_object_name = "jobpost"

    def get_form_kwargs(self) -> Dict[str, Any]:
        kwargs = super().get_form_kwargs()
        if hasattr(self.request.user, "employermodel"):
            kwargs.update(
                {
                    "initial": {
                        "company_name": self.request.user.employermodel.company_name,
                    }
                }
            )
        return kwargs

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.posted_by = self.request.user
        return super().form_valid(form)


class JobpostListView(views.ListView):
    template_name = "core/jobpost/jobpost_list.html"
    model = models.JobPostModel
    context_object_name = "jobposts"

    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset()

        employer = getattr(self.request.user, "employermodel", False)
        if employer:
            qs = qs.filter(posted_by=self.request.user)

        return qs


class JobpostDetailView(views.DetailView):
    template_name = "core/jobpost/jobpost_detail.html"
    model = models.JobPostModel
    context_object_name = "jobpost"


class JobpostUpdateView(views.UpdateView):
    template_name = "core/jobpost/jobpost_update.html"
    model = models.JobPostModel
    form_class = forms.JobPostForm
    success_url = reverse_lazy("core:jobpost_list")


class JobpostDeleteView(views.DeleteView):
    template_name = "core/jobpost/jobpost_delete.html"
    model = models.JobPostModel
    success_url = reverse_lazy("core:jobpost_list")
    context_object_name = "jobpost"


class JobpostListByCategoryView(views.ListView):
    template_name = "core/jobpost/jobpost_list.html"
    model = models.JobPostModel
    context_object_name = "jobposts"

    def get_queryset(self) -> QuerySet[Any]:
        q = super().get_queryset()
        q.filter(id=self.kwargs.get("pk"))
        return q


class DetailView(views.DetailView):
    template_name = "details.html"
    model = models.JobPostModel
    context_object_name = "jobpost"


class AppliedJobCreateView(LoginRequiredMixin, views.CreateView):
    template_name = "applied.html"
    model = models.AppliedModel
    form_class = forms.AppliedForm
    context_object_name = "jobpost"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        jobpost_id = self.kwargs.get("pk")
        self.jobpost = models.JobPostModel.objects.get(id=jobpost_id)
        context["jobpost"] = self.jobpost
        return context

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        jobpost_id = self.kwargs.get("pk")
        self.jobpost = models.JobPostModel.objects.get(id=jobpost_id)
        appliedjob = models.AppliedModel.objects.filter(jobpost__id=jobpost_id)
        if not appliedjob.exists():
            form.instance.user = self.request.user
            form.instance.jobpost = self.jobpost
            return super().form_valid(form)
        return redirect(self.get_success_url())

    def get_success_url(self) -> str:
        jobpost_id = self.kwargs.get("pk")
        appliedjob = models.AppliedModel.objects.filter(jobpost__id=jobpost_id).first()
        return reverse_lazy("core:applied_job_detail", kwargs={"pk": appliedjob.id})


class AppliedJobDetailView(LoginRequiredMixin, views.DetailView):
    template_name = "preview.html"
    model = models.AppliedModel
    context_object_name = "appliedjob"


class AppliedListView(LoginRequiredMixin, views.ListView):
    template_name = "applied_list.html"
    model = models.AppliedModel
    context_object_name = "appliedjobs"

    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset()
        employer = getattr(self.request.user, "employermodel", False)
        jobseeker = getattr(self.request.user, "jobseekermodel", False)
        if employer:
            jobposts = employer.jobposts.values_list("id", flat=True)
            qs = qs.filter(jobpost__id__in=jobposts)
        elif jobseeker:
            qs = qs.filter(user=self.request.user)

        return qs


class MyAppliedListView(views.ListView):
    template_name = "myapplied_list.html"
    model = models.AppliedModel
    context_object_name = "appliedjobs"


# class Register(views.CreateView):
#       template_name = "core/register.html"
# model = models.JobseekerModel
# form_class = forms.JobseekerForm
#       success_url = reverse_lazy("core:home")


# class LoginView(auth_views.LoginView):
#  template_name = "registration/login.html"
# redirect_authenticated_user = True

templates/core/admin_home.html
{% extends 'base.html' %} {% load humanize %}
<!--  -->
{% block content %}
<div class="container py-lg-5 py-3 min-vh-100">
  <div class="row">
    <div class="col">
      <h1 class="text-center">Welcome {{user}}</h1>
      <hr />
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h4>My Jobposts</h4>
      <hr />
    </div>
  </div>
  <div class="row row-cols-lg-5 row-cols-1">
    {% for jobpost in user.jobposts.all %}
    <div class="col">
      <div class="card shadow-sm">
        <div class="card-body">
          <h5 class="card-title">{{jobpost}}</h5>
          <p class="text-muted text-sm fst-italic">
            Created on: {{jobpost.created_on|naturalday}}
          </p>
          <div>
            <a href="{% url 'core:jobpost_detail' jobpost.id %}" class="btn btn-primary">View Details</a>
          </div>
        </div>
      </div>
    </div>
    {% empty %}
    <div class="col">
      <h5 class="mb-3">No Jobposts Found!!</h5>
      <p>
        <a href="" class="btn btn-primary">Add New Jobpost</a>
      </p>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

templates/core/empr_home.html
{%extends 'base_e.html' %}
{% block content %}

<h3>Welcome Employer</h3>



{% endblock content %} 

templates/core/home.html
{% extends 'base.html' %} {% block content %}
<div class="container-lg d-flex flex-column gap-3 py-lg-5 py-3 min-vh-100">
  <div class="row text-black text-center mb-3">
    <div class="col">
      <h1>Find Your Dream Job</h1>
      <hr />
    </div>
  </div>
  <div class="row mb-3">
    <div class="col">
      <div class="card card-body shadow py-lg-5 py-3 overflow-hidden">
        <form
          action="{% url 'core:search' %}"
          class="d-flex"
          method="get"
          role="search"
        >
          {% csrf_token %}
          <div class="form-group w-100">
            <label for="id_job_search" class="form-label">Job Title</label>
            <div class="input-group">
              <input
                class="form-control"
                type="search"
                name="keyword"
                placeholder="Search jobs here..."
                aria-label="Search"
                id="id_job_search"
              />
              <button class="btn btn-outline-success" type="submit">
                Search
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h3>Explore By Category</h3>
      <hr />
    </div>
  </div>
  <div class="row row-cols-lg-5 row-cols-1 g-3">
    {% for category in categories %}
    <div class="col">
      <a
        href="{% url 'core:jobpost_list_by_category' category.id %}"
        class="link"
      >
        <div class="card text-center border-warning">
          <div class="card-body">
            <h4 class="card-title">{{category.name}}</h4>
            <p class="card-text">Vacancies: {{category.no_of_vacancy}}</p>
          </div>
        </div>
      </a>
    </div>
    {% empty%}
    <div class="col">
      <div class="card_body">
        <h5 class="card-title">No category found!</h5>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

templates/core/user_home.html
{%extends 'base.html' %}
{% block content %}
<html>
    <body>
       <h3 class="text-center">Welcome user</h3>
<div class="container-fluid">
    <div class="row row-cols-2">
        <div class="bg-secondary col-auto col-md-2 min-vh-100">
            <div class="bg-dark p-2">
                
                <ul class="nav nav-pills flex-column mt-4">
                    <li class="nav-item">
                        
                            <form action="{% url 'core:search' %}" class="d-flex" method="get" role="search">
                              <input class="form-control me-2" type="search" name="keyword" placeholder="Search" aria-label="Search">
                              <button class="btn btn-outline-success" type="submit">Search</button>
                            </form>
                          
                        
                    </li>


                    <li class="nav-item">
                        <a href="{% url 'core:search' %}" class="nav-link text-blue">
                            <i class="fs-5 fa fa-table-list"><span class="fs-4 d-none d-sm-inline">Search</span></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link text-blue">
                            <i class="fs-5 fa fa-table-list"><span class="fs-4 d-none d-sm-inline">View Applied</span></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'accounts:password_change' %}" class="nav-link text-blue">
                            <i class="fs-5 fa fa-table-list"><span class="fs-4 d-none d-sm-inline">Change password</span></i>
                        </a>
                    </li>
                </ul>

            </div>
            
        </div>
        
    </div>
</div>
    </body>
</html>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>





















{% endblock content %} 